---
- name: Copy a certificate only to group 'webservers'.
  copy:
    src: "{{ certificate_source_path }}"
    dest: "{{ certificate_dest_path }}"
  become: true
  when: inventory_hostname in groups['webservers']

- name: Copy a certificate key only to group 'webservers'.
  copy:
    src: "{{ certificate_key_source_path }}"
    dest: "{{ certificate_key_dest_path }}"
  become: true
  when: inventory_hostname in groups['webservers']
...