---
- name: Install dependencies for Docker
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: latest
  with_items: "{{ docker_dependencies }}"
  when: ansible_os_family == "Debian"
  become: true

# Add GPG key

- name: Add Docker official GPG key
  apt_key:
    url: "{{ docker_gpg_url }}"
    state: present
  when: ansible_os_family == "Debian"
  become: true

# Add Docker repository

- name: Add Docker repository
  apt_repository:
    update_cache: yes
    repo: deb {{ docker_repository_url }} {{ ansible_distribution_release }} stable
  when: ansible_os_family == "Debian"
  become: true

# Install Docker latest version

- name: Install Docker latest version
  apt:
    update_cache: yes
    name: "{{ docker_packages }}"
    state: latest
  when: ansible_os_family == "Debian"
  become: true

# Clean repository

- name: Clean repository
  apt:
    autoclean: yes
    autoremove: yes
  when: ansible_os_family == "Debian"
  become: true

# The docker module needs to be installed for ansible to handle it

- name: Install Python prerequisites
  pip:
    name: docker
  become: true

# Systemd manage Docker service

- name: Enable and start Docker
  systemd:
    state: started
    enabled: yes
    masked: no
    name: docker
  become: true

- name: Add custom bridged net 'devanet'
  docker_network:
    name: devanet
  become: true
  when: inventory_hostname in groups['devanet']
...