---
- name: Add Vagrant official GPG key
  apt_key:
    url: "{{ vagrant_gpg_url }}"
    state: present
  when: ansible_os_family == "Debian"
  become: true

- name: Add Vagrant repository
  apt_repository:
    update_cache: yes
    repo: deb {{ vagrant_repository_url }} {{ ansible_distribution_release }} main
  when: ansible_os_family == "Debian"
  become: true

- name: Install Vagrant with apt
  apt:
    update_cache: yes
    name: "{{ vagrant_packages }}"
    state: latest
  when: ansible_os_family == "Debian"
  become: true
...