---
# tasks file for iptables/add

- name: Add new CHAIN for SSH
  ansible.builtin.iptables:
    chain: ACCEPT-SSH-HTTPS
    chain_management: true
    source: 0.0.0.0/0
    destination_ports: 
    - 22
    - 443
    protocol: tcp
    jump: ACCEPT
    ctstate: NEW,ESTABLISHED
    state: present
    comment: "allow only incoming connections and prevent outbound SSH connection attempts." # would we want that?
  become: true

- name: Reference new chains on INPUT
  ansible.builtin.iptables:
    chain: INPUT
    jump: ACCEPT-SSH-HTTPS
    state: present
  become: true

- name: Set the policy for the INPUT chain to DROP
  ansible.builtin.iptables:
    chain: INPUT
    policy: DROP
    state: present
  become: true