---
# tasks file for iptables/add

- name: Add new CHAIN (accept) for kube-api-server
  ansible.builtin.iptables:
    chain: ACCEPT-KUBE-INTERNAL
    chain_management: true
    source: "127.0.0.1/8"
    destination_ports: 
    - 6443
    protocol: tcp
    jump: ACCEPT
    ctstate: NEW,ESTABLISHED
    state: present
  become: true

- name: Add new CHAIN (accept) for kube-api-server
  ansible.builtin.iptables:
    chain: ACCEPT-KUBE-INTERNAL
    chain_management: true
    source: "10.0.2.0/24" # temp for my vm only - this should be the public on production baremetal server.
    destination_ports: 
    - 6443
    protocol: tcp
    jump: ACCEPT
    ctstate: NEW,ESTABLISHED
    state: present
  become: true

- name: Add new CHAIN (accept) for kube-api-server
  ansible.builtin.iptables:
    chain: ACCEPT-KUBE-INTERNAL
    chain_management: true
    source: "10.42.0.0/24" # the cni0 interface.
    destination_ports: 
    - 6443
    protocol: tcp
    jump: ACCEPT
    ctstate: NEW,ESTABLISHED
    state: present
  become: true

- name: Add new CHAIN (drop) for kube-api-server
  ansible.builtin.iptables:
    chain: DROP-KUBE-EXTERNAL
    chain_management: true
    destination_ports: 
    - 6443 
    protocol: tcp
    jump: DROP
    state: present
  become: true

- name: Reference new CHAIN (accept) for kube-api-server on INPUT
  ansible.builtin.iptables:
    chain: INPUT
    jump: ACCEPT-KUBE-INTERNAL
    state: present
  become: true

- name: Reference new CHAIN (drop) for kube-api-server
  ansible.builtin.iptables:
    chain: INPUT
    jump: DROP-KUBE-EXTERNAL
    state: present
  become: true

- name: Create the file at /usr/local/bin/custom-iptables-rules
  ansible.builtin.copy:
    src: custom-iptables-rules
    dest: /usr/local/bin/custom-iptables-rules
    owner: root
    group: root
    mode: u+rwx,g+rwx,o+x
  become: true

- name: Create the file at /usr/local/bin/clear-custom-iptables-rules
  ansible.builtin.copy:
    src: clear-custom-iptables-rules
    dest: /usr/local/bin/clear-custom-iptables-rules
    owner: root
    group: root
    mode: u+rwx,g+rwx,o+x
  become: true

- name: Enable applying the /usr/local/bin/custom-iptables-rules after machine restart
  ansible.builtin.cron:
    name: "Apply custom iptables rules"
    special_time: reboot
    job: "/usr/local/bin/custom-iptables-rules"
  become: true