services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    hostname: jenkins
    volumes:
      - $HOME/Projects/compose_data/jenkins:/var/jenkins_home:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
    extra_hosts:
    - "nexus.devanet:192.168.56.4"
    network_mode: host
  # dind:
  #   image: docker:dind
  #   container_name: dind
  #   privileged: true
  #   expose:
  #     - 2376
  #   networks:
  #   - jenkins