---
- name: Fetch rbenv
  ansible.builtin.git:
    repo: "{{ rbenv_repository }}"
    dest: "{{ ansible_env.HOME }}/.rbenv"
    update: yes

- name: Source rbenv executable
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    create: true
    insertbefore: 'export SDKMAN_DIR'
    state: present
    line: |
      export PATH="$HOME/.rbenv/bin:$PATH"
      eval "$(rbenv init -)"
  loop:
    - "{{ ansible_env.HOME }}/.profile"
    - "{{ ansible_env.HOME }}/.zprofile"

- name: Install ruby-build plugin
  ansible.builtin.git:
    repo: "{{ ruby_build_repository }}"
    dest: "{{ ansible_env.HOME }}/.rbenv/plugins/ruby-build"
    update: yes
...
