---
- name: Fetch rbenv
  ansible.builtin.git:
    repo: "{{ rbenv_repository }}"
    dest: "{{ ansible_env.HOME }}/bin/rbenv"
    update: yes
    
- name: Source rbenv executable
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    insertbefore: 'export SDKMAN_DIR'
    state: present
    line: |
      export PATH="$HOME/bin/rbenv/bin:$PATH"
      eval "$(rbenv init -)"
  loop:
    - "{{ ansible_env.HOME }}/.profile"
    - "{{ ansible_env.HOME }}/.zprofile"
  ignore_errors: true
    
- name: Install ruby-build plugin
  ansible.builtin.git:
    repo: "{{ ruby_build_repository }}"
    dest: "{{ ansible_env.HOME }}/.rbenv/plugins/ruby-build"
    update: yes
...