---
- hosts: localhost

  vars_files:
    - ../vars.yaml

  tasks:
    - name: "Notify Slack"
      slack:
        token: '{{slack_api_token}}'
        channel: '#devops'
        msg: '@devops-team Databricks Workspace for client `{{client_name}}` at `https://{{workspace_url}}` is ready. Please wait for extra user provisioning confirmation on this thread...'
        color: good
        link_names: 1
