---
- hosts: localhost

  vars_files:
    - ../vars.yaml

  tasks:
    - name: "Notify Slack"
      slack:
        token: '{{slack_api_token}}'
        channel: '#ansible'
        msg: '@data-science-team Storage `{{storage_account_name}}` for client `{{client_name}}` is ready.'
        color: good
        link_names: 1
