---
- name: Make sure autodeploy_dir exists
  file:
    path: "{{autodeploy_dir}}"
    state: directory

- name: Make sure fetch_latest_version.py is on rlib_dir
  copy:
    src: fetch_latest_version.py
    dest: "{{autodeploy_dir}}"
    mode: 0777    

- name: Add remove.R
  lineinfile:
    line: remove.packages("rlib", "/usr/local/lib/R/library")
    path: "{{autodeploy_dir}}/remove.R"
    create: yes
    state: present

- name: Remove current rlib
  shell: R < {{autodeploy_dir}}/remove.R --no-save
  become: true

- name: Execute script that fetches latest rlib_version
  shell: "{{autodeploy_dir}}/fetch_latest_version.py"
  register: rlib_version_latest
  when: rlib_version is not defined

- name: Show the latest version
  debug:
    var: rlib_version_latest.stdout
  when: rlib_version is not defined

- name: Set version
  set_fact:
    rlib_version: "{{rlib_version_latest.stdout}}"
  when: rlib_version is not defined

- name: Add version to a install.R
  lineinfile:
    line: install.packages("{{rlib_dir}}/rlib_{{rlib_version}}.tar.gz",lib="/usr/local/lib/R/library")
    path: "{{autodeploy_dir}}/install.R"
    create: yes
    state: present

- name: Version to be installed
  debug:
    var: rlib_version

- name: Install rlib
  shell: R < {{autodeploy_dir}}/install.R --no-save
  become: true

  # CLEANUP
- name: Remove files
  shell: rm -rf {{autodeploy_dir}}/install.R

- name: Restart R service
  systemd:
    state: restarted
    name: rserverd
  become: true

- name: Notify Slack
  slack:
    token: '{{slack_api_token}}'
    channel: '{{slack_channel}}'
    msg: 'R server updated with rlib: `{{rlib_version}}`'
    color: good
    link_names: 1
...