- name: Create .ssh folder if not exists
  file:
    state: directory
    path: "{{ ansible_env.HOME }}/.ssh"

- name: Add authorised key (for remote connection)
  authorized_key:
    state: present
    user: "{{ username }}"
    key: "{{ lookup('file', 'eos_id_rsa.pub') }}"

- name: Add public SSH key in ~/.ssh
  copy:
    src: eos_id_rsa.pub
    dest: "{{ ansible_env.HOME }}/.ssh"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Add private SSH key in ~/.ssh
  copy:
    src: eos_id_rsa
    dest: "{{ ansible_env.HOME }}/.ssh"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0600

# Provided you are in a Gnome graphical environment only!
# - name: Reload Gnome Keying service to grab the keys
#   systemd:
#    name: gnome-keyring.service
#    scope: user
#    state: restarted

# The following is in case we are not in a Gnome environment which starts the agent by default.

#- name: Enable SSH agent in ~/.profile
#  ansible.builtin.lineinfile:
#    path: "{{item}}"
#    insertbefore: 'export SDKMAN_DIR'
#    state: present
#    line: eval `ssh-agent -s`
#  loop:
#    - "{{ansible_env.HOME}}/.profile"

#- name: Add private SSH key in ~/.profile to be added to ssh-agent
#  ansible.builtin.lineinfile:
#    path: "{{item}}"
#    insertbefore: 'export SDKMAN_DIR'
#    state: present
#    create: yes
#    line: ssh-add $HOME/.ssh/eos_id_rsa
#  loop:
#    - "{{ansible_env.HOME}}/.profile"
