Vagrant.configure("2") do |config|

  config.vm.box = "debian/bullseye64"
  config.vm.define "debian-1"
  config.vm.hostname = "debian-1"
  config.vm.network "private_network", type: "dhcp"
  config.ssh.host = "DevaPC" # use the base host's hostname.
  config.ssh.insert_key = true # do not use the global public image key.
  config.ssh.forward_agent = true # have already the agent keys preconfigured for ease - this setting is for the bootstrap process, not for a client connection later on.

  config.vm.provider "virtualbox" do |vbox|
    vbox.memory = 4096
    vbox.cpus = 4
  end

  # config.vm.provision "ansible" do |ansible|
  #   ansible.playbook = "../../../ansible/playbooks/bootstrap_ansible.yaml"
  #   ansible.inventory_path = "../../../ansible/inventory/hosts.ini"
  #   ansible.extra_vars = {
  #     nodes: "#{config.vm.hostname}",
  #     username: "vagrant",
  #     private_key_ansible_path: "/home/eosantigen/METIS/keys/ansible",
  #     public_key_ansible_path: "/home/eosantigen/METIS/keys/ansible.pub"
  #   }
  #   # ansible.ask_vault_pass = true
  #   # ansible.ask_become_pass = true # for some reason it wasn't requested here.
  # end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../../ansible/playbooks/sonatype_nexus.yaml"
    ansible.inventory_path = "../../../ansible/inventory/hosts.ini"
    ansible.extra_vars = {
      nodes: "#{config.vm.hostname}",
      username: "vagrant",
      sdkman_user: "nexus",
    }
    ansible.verbose = true
  end
end