docker_dependencies:
- apt-transport-https
- ca-certificates
- acl
- unzip
- zip
- curl
- gnupg-agent
- software-properties-common
- python3-setuptools
- python3-pip
docker_packages:
- docker-compose
- docker-compose-plugin
- docker-ce
- docker-ce-cli
- containerd.io
docker_gpg_url: https://download.docker.com/linux/ubuntu/gpg
docker_repository_url: https://download.docker.com/linux/ubuntu