---
# tasks file for iptables/remove

# - name: Set the policy for the INPUT chain to ACCEPT
#   ansible.builtin.iptables:
#     chain: INPUT
#     policy: ACCEPT
#     state: present
#   become: true

- name: De-reference custom chains on INPUT
  ansible.builtin.iptables:
    chain: INPUT
    jump: DROP-KUBE-EXTERNAL
    state: absent
  become: true


- name: De-reference custom chains on INPUT
  ansible.builtin.iptables:
    chain: INPUT
    jump: ACCEPT-KUBE-INTERNAL
    state: absent
  become: true
  
# - name: De-reference custom chains on INPUT
#   ansible.builtin.iptables:
#     chain: OUTPUT
#     jump: DROP-KUBE-EXTERNAL
#     state: absent
#   become: true

# - name: Remove rule from custom chain
#   ansible.builtin.iptables:
#     chain: DROP-KUBE-EXTERNAL
#     chain_management: true
#     source: "!192.168.1.11"
#     destination_ports: 
#     - 6443
#     protocol: tcp
#     jump: DROP
#     ctstate: NEW,ESTABLISHED
#     state: absent
#   become: true

# - name: Remove rule from custom chain
#   ansible.builtin.iptables:
#     chain: DROP-KUBE-EXTERNAL
#     chain_management: true
#     source: "!10.0.2.15"
#     destination_ports: 
#     - 6443
#     protocol: tcp
#     jump: DROP
#     ctstate: NEW,ESTABLISHED
#     state: absent
#   become: true

# - name: Remove rule from custom chain
#   ansible.builtin.iptables:
#     chain: DROP-KUBE-EXTERNAL
#     chain_management: true
#     source: "!127.0.0.1/8"
#     destination_ports: 
#     - 6443
#     protocol: tcp
#     jump: DROP
#     ctstate: NEW,ESTABLISHED
#     state: absent
#   become: true


# - name: Remove rule from custom chain
#   ansible.builtin.iptables:
#     chain: DROP-KUBE-EXTERNAL
#     chain_management: true
#     source: "!10.0.2.15/24"
#     destination_ports: 
#     - 6443
#     protocol: tcp
#     jump: DROP
#     ctstate: NEW,ESTABLISHED
#     state: absent
#   become: true

# - name: Remove custom chain
#   ansible.builtin.iptables:
#     chain: DROP-KUBE-EXTERNAL
#     chain_management: true
#     state: absent
#   become: true