- name: Install prerequisites for Docker
  apt:
    update_cache: yes
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python3-setuptools
    state: latest
  when: ansible_os_family == "Debian"
  become: yes

# Add GPG key

- name: Add Docker official GPG key
  apt_key:
    keyserver: https://download.docker.com/linux/ubuntu/gpg
    id: 0EBFCD88
  when: ansible_os_family == "Debian"
  become: yes

# Add Docker repository

- name: Add Docker repository
  apt_repository:
     repo: deb https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
  when: ansible_os_family == "Debian"
  become: yes

# Install Docker latest version

- name: Install Docker latest version
  apt:
    update_cache: yes
    name:
      - docker-compose
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
  when: ansible_os_family == "Debian"
  become: yes

# Clean repository

- name: Clean repository
  apt:
    autoclean: yes
    autoremove: yes
  when: ansible_os_family == "Debian"
  become: yes

# The docker module needs to be installed for ansible to handle it

- name: Install Python prerequisites
  pip:
    name: docker
  become: yes

# Systemd manage Docker service

- name: Enable and start Docker
  systemd:
    state: started
    enabled: yes
    masked: no
    name: docker
  become: yes

- name: Add custom bridged Docker net 'supernet'
  docker_network:
    name: supernet
  become: yes
