---

- name: Install prerequisites for Docker
  apt:
    update_cache: yes
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python3-setuptools
    state: latest
  when: ansible_os_family == "Debian"
  become: True

# Add GPG key

- name: Add Docker official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_os_family == "Debian"
  become: True

# Add Docker repository

- name: Add Docker repository
  apt_repository:
    update_cache: yes
    repo: deb https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
  when: ansible_os_family == "Debian"
  become: True

# Install Docker latest version

- name: Install Docker latest version
  apt:
    update_cache: yes
    name:
      - docker-compose
      - docker-compose-plugin
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
  when: ansible_os_family == "Debian"
  become: True

# Clean repository

- name: Clean repository
  apt:
    autoclean: yes
    autoremove: yes
  when: ansible_os_family == "Debian"
  become: True

# The docker module needs to be installed for ansible to handle it

- name: Install Python prerequisites
  pip:
    name: docker
  become: True

# Systemd manage Docker service

- name: Enable and start Docker
  systemd:
    state: started
    enabled: yes
    masked: no
    name: docker
  become: True

- name: Add custom bridged net 'devanet'
  docker_network:
    name: devanet
  become: True

...