- name: Create $HOME/bin folder if not exists
  file:
    state: directory
    path: "{{ansible_env.HOME}}/bin"

- name: Install rbenv
  ansible.builtin.git:
    repo: https://github.com/rbenv/rbenv.git
    dest: "{{ansible_env.HOME}}/bin/rbenv"
    update: yes
    
- name: Source rbenv executable
  ansible.builtin.lineinfile:
    path: "{{item}}"
    insertbefore: 'export SDKMAN_DIR'
    state: present
    line: |
      export PATH="$HOME/bin/rbenv/bin:$PATH"
      eval "$(rbenv init - bash)"
  loop:
    - "{{ansible_env.HOME}}/.profile"
    - "{{ansible_env.HOME}}/.bashrc"
    - "{{ansible_env.HOME}}/.zshrc"
    
- name: Install ruby-build plugin
  ansible.builtin.git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: "{{ansible_env.HOME}}/.rbenv/plugins/ruby-build"
    update: yes
