---
- name: Config $ZSH/oh-my-zsh.sh
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    create: yes
    insertbefore: 'source $ZSH/oh-my-zsh.sh'
    state: present
    line: |
      source $HOME/.zprofile
  loop:
    - "{{ ansible_env.HOME }}/.zshrc"
...