---
- name: Config $ZSH/oh-my-zsh.sh
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    create: yes
    insertbefore: 'source $ZSH/oh-my-zsh.sh'
    state: present
    line: |
      source $HOME/.zprofile
  loop:
    - "{{ ansible_env.HOME }}/.zshrc"
  tags:
  - zsh

- name: Config $HOME/.(z)profile
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    create: yes
    state: present
    line: |
      # set PATH so it includes user's private bin if it exists
      if [ -d "$HOME/bin" ] ; then
      PATH="$HOME/bin:$PATH"
      fi

      # set PATH so it includes user's private bin if it exists
      if [ -d "$HOME/.local/bin" ] ; then
      PATH="$HOME/.local/bin:$PATH"
      fi

      alias gitl="git log --oneline --graph --abbrev-commit --decorate --date=relative --branches --pretty=format:'%C(bold yellow)%h %C(auto)%d%C(reset) %s %C(italic magenta)(%as) %C(blue)<%cn>' --all"
  loop:
    - "{{ ansible_env.HOME }}/.zprofile"
    - "{{ ansible_env.HOME }}/.profile"
  tags:
  - zsh
...