---
-
  hosts: "{{ nodes }}"
  roles:
    # - configurations/mounts
    - configurations/ssh
    - configurations/git
    - configurations/config_files
  vars_files:
    - ../inventory/variables.yaml

  tags: [ config ]
...
