---
-
  hosts: "{{ node }}"

  roles:
    - install_software
    - install_docker
    - setup_configurations/git
    - setup_configurations/ssh
    - setup_configurations/config_files

  vars_prompt:
    - name: node
      prompt: host || host-group
      private: False

  vars_files:
    - ../params/variables.yaml
...