---

- hosts: "{{host}}"

  roles:
    - install_software
    - install_docker
    - setup_configurations/git
    - setup_configurations/ssh

  vars_prompt:
    - name: host
      prompt: host || host-group
      private: no

  vars_files:
    - ../params/variables.yaml
