---
- include_vars: variables.yaml

####### APT #######

- name: Add OpenNebula repository
  apt_repository:
    state: present
    validate_certs: no
    repo: deb https://downloads.opennebula.org/repo/5.9/Ubuntu/19.10 stable opennebula
  when: ansible_os_family == "Debian"

- name: Add OpenNebula repository key
  apt_key:
    url: https://downloads.opennebula.org/repo/repo.key
    state: present
  when: ansible_os_family == "Debian"

- name: Install OpenNebula packages & dependencies
  apt:
    update_cache: yes
    name:
      - opennebula-node
      - opennebula-sunstone
      - opennebula-gate
      - opennebula-flow
      - opennebula-tools
      - opennebula-common
      - opennebula
      - libvirt-daemon
    state: latest
  when: ansible_os_family == "Debian"

- name: Install dependencies for OpenNebula Gems
  apt:
    name:
      - libsqlite3-dev
      - curl
      - libxml2-dev
      - libxslt1-dev
      - ruby-dev
      - gcc
      - g++
      - make
    state: latest
  when: ansible_os_family == "Debian"

- name: Install OpenNebula Gems
  shell: yes | /usr/share/one/install_gems

- name: Change default ONE password
  shell: echo "oneadmin:{{one_password}}" > /home/{{username}}/.one/one_auth

- name: Enable and start daemons
  systemd:
    state: started
    enabled: yes
    masked: no
    name: "{{item}}"
  with_items:
    - opennebula
    - opennebula-sunstone
    - libvirtd

- name: Grab OpenNebula information
  shell: oneuser show
  become: true
  register: one_info

- name: Show OpenNebula information
  debug:
    var: one_info.stdout_lines
