---
-
  hosts: "{{ nodes }}"
  roles:
    - python
  tags: [ python, git ]
  vars:
    pyenv_repository: https://github.com/pyenv/pyenv.git
  vars_prompt:
    - name: pyenv_python_version
      private: false
      prompt: Type a Python version to install with pyenv or press enter for the default
      default: 3.10.4
...