- name: Create .ssh folder if not exists
  file:
    state: directory
    path: "{{ansible_env.HOME}}/.ssh"

- name: Add authorised key (for remote connection)
  authorized_key:
    state: present
    user: "{{username}}"
    key: "{{ lookup('file', 'eos_id_rsa.pub') }}"

- name: Add public SSH key in ~/.ssh
  copy:
    src: eos_id_rsa.pub
    dest: "{{ansible_env.HOME}}/.ssh"
    owner: "{{username}}"
    group: "{{username}}"

- name: Add private SSH key in ~/.ssh
  copy:
    src: eos_id_rsa
    dest: "{{ansible_env.HOME}}/.ssh"
    owner: "{{username}}"
    group: "{{username}}"
    mode: 0600

- name: Enable SSH agent in ~/.bashrc
  ansible.builtin.lineinfile:
    path: "{{item}}"
    insertbefore: 'export SDKMAN_DIR'
    state: present
    line: eval `ssh-agent -s`
  loop:
    - "{{ansible_env.HOME}}/.profile"
    - "{{ansible_env.HOME}}/.bashrc"
    - "{{ansible_env.HOME}}/.zshrc"

- name: Add private SSH key in ~/.bashrc to be added to ssh-agent
  ansible.builtin.lineinfile:
    path: "{{item}}"
    insertbefore: 'export SDKMAN_DIR'
    state: present
    create: yes
    line: ssh-add $HOME/.ssh/eos_id_rsa
  loop:
    - "{{ansible_env.HOME}}/.profile"
    - "{{ansible_env.HOME}}/.bashrc"
    - "{{ansible_env.HOME}}/.zshrc"
