---

### Self CA.

- name: Create private key with password protection
  community.crypto.openssl_privatekey:
    path: "{{ ca_key_path }}"

- name: Create certificate signing request (CSR) for CA certificate
  community.crypto.openssl_csr:
    path: "{{ ca_csr_path }}"
    privatekey_path: "{{ ca_key_path }}"
    common_name: "{{ ca_common_name }}"
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: true

- name: Create self-signed CA certificate from CSR
  community.crypto.x509_certificate:
    path: "{{ ca_path }}"
    csr_path: "{{ ca_csr_path }}"
    privatekey_path: "{{ ca_key_path }}"
    provider: selfsigned

### Self Cert signed by the Self CA.

- name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
  community.crypto.openssl_privatekey:
    path: "{{ certificate_key_path }}"

- name: Generate an OpenSSL Certificate Signing Request
  community.crypto.openssl_csr:
    path: "{{ certificate_csr_path }}"
    privatekey_path: "{{ certificate_key_path }}"
    common_name: "{{ certificate_common_name }}"
    organization_name: DevaNet
    subject_alt_name:
      - "DNS:devaweb.devanet"
      - "DNS:*.devanet"
      - "DNS:*.local"

- name: Generate a Self Signed OpenSSL certificate
  community.crypto.x509_certificate:
    path: "{{ certificate_path }}"
    privatekey_path: "{{ certificate_key_path }}"
    csr_path: "{{ certificate_csr_path }}"
    provider: ownca
    ownca_path: "{{ ca_path }}"
    ownca_privatekey_path: "{{ ca_key_path }}"
...
