- name: Install software with APT
  apt:
    update_cache: yes
    name:
      - curl
      - zsh
      - conky
      - vim
      - git
      - tree
      - ffmpeg
      - moc
      - fonts-powerline
    state: latest
  when: ansible_os_family == "Debian"
  become: yes

- name: Install software with snap
  snap:
    name:
      - code
      - postman
      - intellij-idea-community
    classic: yes
  when: ansible_os_family == "Debian"
  become: yes

- name: Install OMZ
  shell: curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | zsh -
  ignore_errors: yes

- name: Install OMZ Powerlevel
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: $ZSH_CUSTOM/themes/powerlevel10k
  ignore_errors: yes

- name: Install asdf
  ansible.builtin.git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "{{ansible_env.HOME}}/.asdf"

- name: Configure asdf
  ansible.builtin.lineinfile:
    path: "{{item}}"
    line: . $HOME/.asdf/asdf.sh
    create: yes
  loop:
    - "{{ansible_env.HOME}}/.profile"

- name: Install SDKMan
  shell: curl -s "https://get.sdkman.io" | bash

- name: Configure SDKMan
  ansible.builtin.lineinfile:
    path: "{{item}}"
    insertafter: "EOF"
    line: |
      export SDKMAN_DIR="$HOME/.sdkman"
      [[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
  loop:
    - "{{ansible_env.HOME}}/.profile"