Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"
  config.vm.define "ubuntu-jammy"
  config.vm.hostname = "ubuntu-jammy"
  # config.vm.network "private_network", type: "dhcp"
  # config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.ssh.host = "localhost" # use the base host's hostname.
  config.ssh.insert_key = true # do not use the global public image key.
  config.ssh.forward_agent = true # have already the agent keys preconfigured for ease - this setting is for the bootstrap process, not for a client connection later on.

  config.vm.provider "virtualbox" do |vbox|
    vbox.memory = 4096
    vbox.cpus = 4
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../../ansible/playbooks/python.yaml"
    ansible.inventory_path = "../../../ansible/inventory/hosts.ini"
    ansible.extra_vars = {
      nodes: "#{config.vm.hostname}",
      username: "vagrant",
    }
  end
end