Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"
  config.vm.define "ubuntu-jammy"
  config.vm.hostname = "ubuntu-jammy"
  config.vm.network "public_network", ip: "192.168.1.11" # enables Bridge mode!
  # config.vm.network "private_network", type: "dhcp"
  # config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.ssh.host = "localhost" # use the base host's hostname.
  config.ssh.insert_key = true # do not use the global public image key.
  config.ssh.forward_agent = true # have already the agent keys preconfigured for ease - this setting is for the bootstrap process, not for a client connection later on.

  config.vm.provider "virtualbox" do |vbox|
    vbox.memory = 1024
    vbox.cpus = 1
  end

  # THIS IS TO BE RAN ONLY ONCE FOR 1st PROVISIONING ONLY.
  # config.vm.provision "ansible" do |ansible|
  #   ansible.playbook = "../../../ansible/playbooks/bootstrap_ansible.yaml"
  #   ansible.inventory_path = "../../../ansible/inventory/hosts.ini"
  #   ansible.extra_vars = {
  #     nodes: "#{config.vm.hostname}",
  #     username: "vagrant",
  #     private_key_ansible_path: "/home/eosantigen/.ssh/eos_id_rsa",
  #     public_key_ansible_path: "/home/eosantigen/.ssh/eos_id_rsa.pub"
  #   }
  # end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../../ansible/playbooks/iptables.yaml"
    ansible.inventory_path = "../../../ansible/inventory/hosts.ini"
    ansible.extra_vars = {
      nodes: "#{config.vm.hostname}",
      username: "vagrant",
    }
    ansible.tags = ["remove"]
  end
end
