---
- name: Fetch SDKMan installation file.
  ansible.builtin.get_url:
    url: https://get.sdkman.io
    dest: /tmp/sdkman
    owner: "{{ sdkman_user }}"
    group: "{{ sdkman_user }}"
    mode: 0777
  become: true

- name: Install SDKMan.
  ansible.builtin.shell: /tmp/sdkman
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ sdkman_user }}"

- name: Configure SDKMan.
  ansible.builtin.shell: |
    export SDKMAN_DIR="$HOME/.sdkman";
    export SDKMAN_AUTO_ANSWER=true;
    export SDKMAN_SELFUPDATE_ENABLE=false;
    source "$HOME/.sdkman/bin/sdkman-init.sh"
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ sdkman_user }}"
...