services:
  afs_size_alerter:
    image: devops/afs-size-alerter
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER: eosantigen
        WORKDIR: $HOME/app
        APP_NAME: afs_size_slack_alerter
    container_name: afs_size_slack_alerter
    hostname: afs_size_slack_alerter
    environment:
      APP_NAME: afs_size_slack_alerter
      CONN_STR: ${CONN_STR}
      AFS: # fileshare names separated by comma
      SLACK_WEBHOOK_TOKEN: ${SLACK_WEBHOOK_TOKEN}