---
- name: Install a Python version with pyenv.
  ansible.builtin.shell: source $HOME/.profile && yes | pyenv install {{ pyenv_python_version }}
  args:
    executable: /bin/bash
  when: pyenv_python_version is defined

- name: Set a global Python version with pyenv.
  ansible.builtin.shell: source $HOME/.profile && pyenv global {{ pyenv_python_version }}
  args:
    executable: /bin/bash
  when: pyenv_python_version is defined

- name: Install virtualenv with pip.
  ansible.builtin.shell: source $HOME/.profile && python -m pip install virtualenv
  args:
    executable: /bin/bash
  when: pyenv_python_version is defined

# virtual-env is at the developer's choice
- name: All set.
  ansible.builtin.debug:
    msg: "OK. You may now setup your code with a virtualenv under Python {{ pyenv_python_version }}. Happy coding!"
  when: pyenv_python_version is defined
...