---
- name: Install software with apt
  apt:
    update_cache: yes
    name: "{{ apt_packages }}"
    state: latest
  when: ansible_os_family == "Debian"
  become: true

- name: Install software with snap
  snap:
    name: "{{ snap_packages }}"
    classic: yes
  when: ansible_os_family == "Debian"
  become: true
  tags:
    - snap

# ZSH
# ~/.zshrc must contain this:
# plugins=(git zsh-autosuggestions zsh-syntax-highlighting)
- name: Fetch OMZ
  shell: curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | zsh -
  tags:
    - zsh
  ignore_errors: true

- name: Fetch OMZ Powerlevel
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ ansible_env.ZSH }}/custom/themes/powerlevel10k"
  tags:
    - zsh
  ignore_errors: true

- name: Fetch OMZ plugin autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ ansible_env.ZSH }}/custom/plugins/zsh-autosuggestions"
  tags:
    - zsh
  ignore_errors: true

- name: Fetch OMZ plugin syntax-highlighting
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ ansible_env.ZSH }}/custom/plugins/zsh-syntax-highlighting"
  tags:
    - zsh
  ignore_errors: true

- name: Fetch asdf
  ansible.builtin.git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "{{ ansible_env.HOME }}/.asdf"
    update: yes
  ignore_errors: true

- name: Configure asdf
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    line: . $HOME/.asdf/asdf.sh
    create: yes
  loop:
    - "{{ ansible_env.HOME }}/.profile"
    - "{{ ansible_env.HOME }}/.zprofile"
...
