---
- name: Fetch pyenv
  ansible.builtin.git:
    repo: "{{ pyenv_repository }}"
    dest: "{{ ansible_env.HOME }}/.pyenv"
    update: yes
    
- name: Source pyenv executable
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    create: yes
    insertbefore: 'export SDKMAN_DIR'
    state: present
    line: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
  loop:
    - "{{ ansible_env.HOME }}/.profile"
    - "{{ ansible_env.HOME }}/.zprofile"

- name: Install prerequisites for building Python from source with pyenv
  apt:
    update_cache: yes
    name:
      - build-essential
      - libsasl2-dev
      - libssl-dev
      - libsqlite3-dev
      - libncurses-dev
      - liblzma-dev
      - libbz2-dev
      - libffi-dev
      - libreadline-dev
      - zlib1g-dev
    state: latest
  when: ansible_os_family == "Debian"
  become: true
...