---
- name: Fetch pyevn
  ansible.builtin.git:
    repo: "{{ pyenv_repository }}"
    dest: "{{ ansible_env.HOME }}/bin/pyenv"
    update: yes
    
- name: Source pyenv executable
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    create: yes
    insertbefore: 'export SDKMAN_DIR'
    state: present
    line: |
      export PYENV_ROOT="$HOME/bin/pyenv"
      command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
  loop:
    - "{{ ansible_env.HOME }}/.profile"
  ignore_errors: true
...