# Generated by Django 4.1 on 2023-01-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag', models.CharField(default='-', max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=33)),
                ('time', models.CharField(max_length=33)),
                ('task', models.CharField(max_length=500)),
                ('tags', models.CharField(default='-', max_length=100, null=True)),
            ],
        ),
    ]
