# Generated by Django 4.1 on 2023-01-15 10:58

from django.db import migrations, models
import logbook.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag', models.CharField(default='-', max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
            managers=[
                ('objects', logbook.models.TagManager()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
                ('task', models.CharField(max_length=500)),
                ('tags', models.CharField(default='-', max_length=100, null=True)),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
    ]
