# Generated by Django 4.1 on 2023-01-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-time',)},
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
