# Generated by Django 4.1 on 2023-01-15 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tag',
            managers=[
            ],
        ),
    ]
