# Generated by Django 4.1 on 2023-01-15 11:02

from django.db import migrations
import logbook.models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_alter_tag_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tag',
            managers=[
                ('objects', logbook.models.TagManager()),
            ],
        ),
    ]
