# Generated by Django 4.1 on 2023-01-15 11:06

from django.db import migrations

TAG_VALUES = {
'aks',
'prod',
'dev',
'cicd',
'hardware',
'embedded'
}

def add_tag_values(apps, schema_editor):

    Tag = apps.get_model('logbook', 'Tag')

    Tag.objects.populate_tags(TAG_VALUES)

class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_alter_tag_managers'),
    ]

    operations = [
        migrations.RunPython(add_tag_values),
    ]